-- ============================================================
--  „Un an împreună" ♾️ — tabelul pentru drumul serpuit
--
--  CE FACE: creează UN TABEL NOU, gol, numit drum_amintiri.
--  CE NU FACE: nu atinge, nu modifică și nu șterge nimic din
--  ce ai deja — nici Poze, nici LoginUsers, nici pozele din
--  Storage. Pozele sunt doar citite din galeria existentă.
--
--  CUM SE RULEAZĂ (o singură dată):
--    Supabase → proiectul tău → SQL Editor → New query
--    → lipești tot fișierul ăsta → Run
-- ============================================================

create table if not exists public.drum_amintiri (
    id          bigint generated by default as identity primary key,
    poza_id     bigint,                       -- id-ul din tabelul Poze (ca să știm ce poze sunt deja pe drum)
    photo_url   text not null,                -- URL-ul public al pozei, copiat din Poze
    title       text,                         -- titlu scurt (ex. „Prima noastră vacanță")
    message     text,                         -- mesajul de sub poză
    photo_date  date,                         -- data amintirii
    ordine      integer not null default 0,   -- poziția pe drum
    created_at  timestamptz not null default now()
);

create index if not exists drum_amintiri_ordine_idx
    on public.drum_amintiri (ordine, id);

-- Aceleași reguli de acces ca la celelalte tabele ale site-ului:
-- site privat, cheie publishable, citire și scriere din browser.
alter table public.drum_amintiri enable row level security;

drop policy if exists "drum_amintiri_all" on public.drum_amintiri;
create policy "drum_amintiri_all"
    on public.drum_amintiri
    for all
    to anon, authenticated
    using (true)
    with check (true);

-- Supabase acordă de obicei automat drepturile astea tabelelor noi.
-- Le punem explicit ca să fim siguri.
grant select, insert, update, delete on public.drum_amintiri to anon, authenticated;

-- Fără linia asta, API-ul mai poate răspunde o vreme cu
-- „Could not find the table 'public.drum_amintiri' in the schema cache".
notify pgrst, 'reload schema';
